"""empty message

Revision ID: 3527b69448fe
Revises: 
Create Date: 2026-03-07 02:06:05.161896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3527b69448fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.drop_table('student_courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_courses',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('student_courses_course_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('student_courses_student_id_fkey')),
    sa.PrimaryKeyConstraint('student_id', 'course_id', name=op.f('student_courses_pkey'))
    )
    op.drop_table('student_course')
    # ### end Alembic commands ###
